# https://github.com/amannn/action-semantic-pull-request
name: Lint PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please does not start with an uppercase character
            and follows conventional commits naming.
          validateSingleCommit: true
